language: objective-c
osx_image: xcode8

script:
  - xcodebuild -workspace Monoid.xcworkspace -scheme Monoid-Mac test
  - xcodebuild -workspace Monoid.xcworkspace -scheme Monoid-iOS -destination "platform=iOS Simulator,name=iPhone 6" test
  - xcodebuild -workspace Monoid.xcworkspace -scheme Monoid-TVOS -destination "platform=tvOS Simulator,name=Apple TV 1080p" test
